### PR TITLE
CV-142681 Chess-Game Do not allow pieces in rook position to castle

### PR DESCRIPTION
**Pull request by andreij**
In case of odds game or games with custom FEN such as `q3k2q/pbpqppbp/1pnp1np1/8/8/1PNP1NP1/PBPQPPBP/Q3K2Q w KQkq - 2 9` check that there are actually rooks in the board to decide if a king can castle or not.

### CODE REVIEW

**Review by jmogilner — APPROVED** [review]
Looks ok, but I would love to see a test where he can castle one side, but not the other

**Comment by andreij** [comment]
@jmogilner Thanks for your suggestion to improve tests, it turned out `w1r` isn't the king side rook as I wrongly supposed but the first rook found in the chessboard. So I've refactored code accordingly.

**Review by jmogilner — APPROVED** [review]
Makes more sense now. Thanks

**Comment by marcosdsanchez** [comment]
Have you verified that the code works correctly for Fischer random chess castling? https://en.wikipedia.org/wiki/Fischer_random_chess#Castling_rules

**Comment by marcosdsanchez** [comment]
I don't think that this will work for chess960. Can you please create a test based on the example I shared in the link below?

**Comment by andreij** [comment]
@marcosdsanchez Thanks for heads up, reverted in #39

**Pull request merged**
